version: '3.1'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:mysql://db:3306/luizalabs?allowPublicKeyRetrieval=true&useSSL=false
      JDBC_USER: root
      JDBC_PASSWORD: admin
    ports:
      - 8080:8080
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql